fix_items1 = "//div[normalize-space()='Sauce Labs Fleece Jacket']"
fix_items2 = "//div[normalize-space()='Sauce Labs Backpack']"
fix_items3 = "//div[normalize-space()='Sauce Labs Bolt T-Shirt']"
payment_info = "//div[normalize-space()='SauceCard #31337']"
ship_info = "//div[normalize-space()='Free Pony Express Delivery!']"
price_total = "//div[@class='summary_total_label']"
finish_btn = "//button[@id='finish']"
success_co_text = "//span[@class='title']"
thanks_text = "//h2[@class='complete-header']"
msg_text = "//div[@class='complete-text']"
ceklis_img = "//img[@alt='Pony Express']"